# **6CS012 - Worksheet 0**
## A review on Python programming and NumPy for Deep Learning


# **Section 4: Exercises on Python (To-Do-Task)**
## **4.1 Exercise on Functions**

### Task 1: Measurement Unit Converter


In [ ]:
def convert_length(value, direction):

    # Converts length between meters and feet.

    if direction == 'm_to_ft':
        return value * 3.28084
    elif direction == 'ft_to_m':
        return value / 3.28084

def convert_weight(value, direction):

    # Converts weight between kilograms and pounds.

    if direction == 'kg_to_lbs':
        return value * 2.20462
    elif direction == 'lbs_to_kg':
        return value / 2.20462

def convert_volume(value, direction):

    # Converts volume between liters and gallons.

    if direction == 'l_to_gal':
        return value * 0.264172
    elif direction == 'gal_to_l':
        return value / 0.264172

def unit_converter():

    # Main function to prompt user and perform unit conversion.

    print("Choose conversion type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    try:
        choice = input("Enter 1, 2, or 3: ")

        if choice == '1':
            print("1. Meters to Feet  2. Feet to Meters")
            sub = input("Enter 1 or 2: ")
            value = float(input("Enter value: "))
            if sub == '1':
                print(f"{value} m = {convert_length(value, 'm_to_ft'):.4f} ft")
            elif sub == '2':
                print(f"{value} ft = {convert_length(value, 'ft_to_m'):.4f} m")
            else:
                print("Invalid sub-choice.")

        elif choice == '2':
            print("1. KG to LBS  2. LBS to KG")
            sub = input("Enter 1 or 2: ")
            value = float(input("Enter value: "))
            if sub == '1':
                print(f"{value} kg = {convert_weight(value, 'kg_to_lbs'):.4f} lbs")
            elif sub == '2':
                print(f"{value} lbs = {convert_weight(value, 'lbs_to_kg'):.4f} kg")
            else:
                print("Invalid sub-choice.")

        elif choice == '3':
            print("1. Liters to Gallons  2. Gallons to Liters")
            sub = input("Enter 1 or 2: ")
            value = float(input("Enter value: "))
            if sub == '1':
                print(f"{value} L = {convert_volume(value, 'l_to_gal'):.4f} gal")
            elif sub == '2':
                print(f"{value} gal = {convert_volume(value, 'gal_to_l'):.4f} L")
            else:
                print("Invalid sub-choice.")

        else:
            print("Invalid choice. Please enter 1, 2, or 3.")

    except ValueError:
        print("Invalid input. Please enter a numeric value.")

unit_converter()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter 1, 2, or 3: 1
1. Meters to Feet  2. Feet to Meters
Enter 1 or 2: 1
Enter value: 1.2
1.2 m = 3.9370 ft


### Task 2: Mathematical Operations on a List

In [ ]:
def find_sum(numbers):

    # Returns the sum of a list of numbers.

    total = 0
    for n in numbers:
        total += n
    return total

def find_average(numbers):

    # Returns the average of a list of numbers.

    return find_sum(numbers) / len(numbers)

def find_maximum(numbers):

    # Returns the maximum value in a list.

    max_val = numbers[0]
    for n in numbers:
        if n > max_val:
            max_val = n
    return max_val

def find_minimum(numbers):

    # Returns the minimum value in a list.

    min_val = numbers[0]
    for n in numbers:
        if n < min_val:
            min_val = n
    return min_val

def math_operations():

    # Prompts user to choose an operation and input numbers, then performs the operation.

    print("Choose an operation:")
    print("1. Sum  2. Average  3. Maximum  4. Minimum")

    try:
        choice = input("Enter 1, 2, 3, or 4: ")
        raw = input("Enter numbers separated by spaces: ")
        numbers = [float(x) for x in raw.split()]

        if not numbers:
            print("List is empty.")
            return

        if choice == '1':
            print(f"Sum: {find_sum(numbers)}")
        elif choice == '2':
            print(f"Average: {find_average(numbers)}")
        elif choice == '3':
            print(f"Maximum: {find_maximum(numbers)}")
        elif choice == '4':
            print(f"Minimum: {find_minimum(numbers)}")
        else:
            print("Invalid choice.")

    except ValueError:
        print("Invalid input. Please enter numeric values.")
    except ZeroDivisionError:
        print("Cannot compute average of an empty list.")

math_operations()

Choose an operation:
1. Sum  2. Average  3. Maximum  4. Minimum
Enter 1, 2, 3, or 4: 4
Enter numbers separated by spaces: 10 100 5 23
Minimum: 5.0


## **4.2 Exercise on List Manipulation**

In [ ]:
# 1. Extract Every Other Element
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1, 2, 3, 4, 5, 6]))

[1, 3, 5]


In [ ]:
# 2. Slice a Sublist
def get_sublist(lst, start, end):
    return lst[start:end+1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


In [ ]:
# 3. Reverse a List Using Slicing
def reverse_list(lst):
    return lst[::-1]

print(reverse_list([1, 2, 3, 4, 5]))

[5, 4, 3, 2, 1]


In [ ]:
# 4. Remove the First and Last Elements
def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


In [ ]:
# 5. Get the First n Elements
def get_first_n(lst, n):
    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


In [ ]:
# 6. Extract Elements from the End
def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]


In [ ]:
# 7. Extract Elements in Reverse Order
def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


## **4.3 Exercise on Nested Lists**

In [ ]:
# 1. Flatten a Nested List
def flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

print(flatten([[1, 2], [3, 4], [5]]))

[1, 2, 3, 4, 5]


In [ ]:
# 2. Accessing Nested List Elements
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(access_nested_element(lst, [1, 2]))

6


In [ ]:
# 3. Sum of All Elements in a Nested List
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1, 2], [3, [4, 5]], 6]))

21


In [ ]:
# 4. Remove Specific Element from a Nested List
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

print(remove_element([[1, 2], [3, 2], [4, 5]], 2))

[[1], [3], [4, 5]]


In [ ]:
# 5. Find the Maximum Element in a Nested List
def find_max(lst):
    all_elements = flatten(lst)
    return max(all_elements)

print(find_max([[1, 2], [3, [4, 5]], 6]))

6


In [ ]:
# 6. Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))

3


In [ ]:
# 7. Flatten a List of Lists of Lists (deep flatten)
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# 8. Nested List Average
def average_nested(lst):
    all_elements = flatten(lst)
    return sum(all_elements) / len(all_elements)

print(average_nested([[1, 2], [3, 4], [5, 6]]))

3.5


# **Section 10: NumPy Exercises**
## **10.1 Basic Vector and Matrix Operations**

### Problem 1: Array Creation

In [ ]:
import numpy as np

# 1. Empty array 2x2
empty_arr = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_arr)

# 2. All ones array 4x2
ones_arr = np.ones((4, 2))
print("\n2. Ones 4x2 array:\n", ones_arr)

# 3. Array filled with a fill value
full_arr = np.full((3, 3), 7)
print("\n3. Array filled with 7:\n", full_arr)

# 4. Zeros array
given = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like = np.zeros_like(given)
print("\n4. Zeros like given array:\n", zeros_like)

# 5. Ones array with same shape as a given array
ones_like = np.ones_like(given)
print("\n5. Ones like given array:\n", ones_like)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print("\n6. NumPy array from list:", np_array)

1. Empty 2x2 array:
 [[5.03870118e-315 0.00000000e+000]
 [5.36751337e-317 5.36751337e-317]]

2. Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like given array:
 [[0 0 0]
 [0 0 0]]

5. Ones like given array:
 [[1 1 1]
 [1 1 1]]

6. NumPy array from list: [1 2 3 4]


### Problem 2: Array Manipulation

In [ ]:
# 1. Array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("1. Array 10 to 49:\n", arr1)

# 2. 3x3 matrix with values 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0 to 8):\n", arr2)

# 3. 3x3 identity matrix
identity = np.eye(3)
print("\n3. 3x3 Identity matrix:\n", identity)

# 4. Random array of size 30 and its mean
rand_arr = np.random.random(30)
print("\n4. Random array mean:", rand_arr.mean())

# 5. 10x10 random array, min and max
rand_10x10 = np.random.random((10, 10))
print("\n5. 10x10 array - Min:", rand_10x10.min(), "Max:", rand_10x10.max())

# 6. Zero array of size 10, replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\n6. Zero array with 5th element = 1:\n", zero_arr)

# 7. Reverse the array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:", reversed_arr)

# 8. 2D array with 1 on border and 0 inside
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("\n8. Array with 1 on border and 0 inside:\n", border_arr)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. Checkerboard 8x8:\n", checkerboard)

1. Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array mean: 0.4452945778203746

5. 10x10 array - Min: 0.029566769466042087 Max: 0.9961971993690747

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array: [0 4 0 0 2 1]

8. Array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard 8x8:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem 3: Array Operations

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add
print("1. x + y:\n", x + y)

# 2. Subtract
print("\n2. x - y:\n", x - y)

# 3. Multiply with integer
print("\n3. x * 3:\n", x * 3)

# 4. Square of each element
print("\n4. x squared:\n", np.square(x))

# 5. Dot products
print("\n5a. Dot product v and w:", np.dot(v, w))
print("5b. Dot product x and v:\n", np.dot(x, v))
print("5c. Dot product x and y:\n", np.dot(x, y))

# 6. Concatenate x and y along rows (axis=0), v and w along columns
concat_xy = np.vstack((x, y))
print("\n6a. x and y concatenated along rows:\n", concat_xy)

concat_vw = np.concatenate((v, w))
print("6b. v and w concatenated:", concat_vw)

# 7. Concatenate x and v - will raise an error
print("\n7. Trying to concatenate x and v:")
try:
    result = np.concatenate((x, v))
except ValueError as e:
    print(f"Error: {e}")
    print("Reason: x has shape (2,2) and v has shape (2,). They have different dimensions, so concatenation fails.")

1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]

4. x squared:
 [[ 1  4]
 [ 9 25]]

5a. Dot product v and w: 219
5b. Dot product x and v:
 [29 77]
5c. Dot product x and y:
 [[19 22]
 [50 58]]

6a. x and y concatenated along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. v and w concatenated: [ 9 10 11 12]

7. Trying to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x has shape (2,2) and v has shape (2,). They have different dimensions, so concatenation fails.


### Problem 4: Matrix Operations

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A_inv = I
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
print("1. A * A_inv (should be Identity):\n", np.round(result))

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("AB == BA:", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)
print("\n3. (AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)
print("(AB)^T == B^T * A^T:", np.array_equal(AB_T, BT_AT))

1. A * A_inv (should be Identity):
 [[1. 0.]
 [0. 1.]]

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA: False

3. (AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
(AB)^T == B^T * A^T: True


In [ ]:
"""
Solve system of linear equations:
2x - 3y + z = -1
x - y + 2z = -3
3x + y - z = 9

"""

A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3,  1, -1]])

B_eq = np.array([-1, -3, 9])

# Method 1: Using inverse
A_inv = np.linalg.inv(A_eq)
X = np.dot(A_inv, B_eq)
print("Solution using Inverse method (x, y, z):", X)

# Method 2: Using np.linalg.solve
X2 = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve (x, y, z):", X2)

Solution using Inverse method (x, y, z): [ 2.  1. -2.]
Solution using np.linalg.solve (x, y, z): [ 2.  1. -2.]


## **10.2 Experiment: How Fast is NumPy?**

In [ ]:
import time

SIZE = 1_000_000

# 1. Element-wise Addition

list_a = list(range(SIZE))
list_b = list(range(SIZE))

# Python list
start = time.time()
result = [list_a[i] + list_b[i] for i in range(SIZE)]
print(f"1. Addition - Python List: {time.time() - start:.5f} sec")

# NumPy
np_a = np.array(list_a)
np_b = np.array(list_b)
start = time.time()
result = np_a + np_b
print(f"1. Addition - NumPy:       {time.time() - start:.5f} sec")

1. Addition - Python List: 0.10777 sec
1. Addition - NumPy:       0.01726 sec


In [ ]:
# 2. Element-wise Multiplication

# Python list
start = time.time()
result = [list_a[i] * list_b[i] for i in range(SIZE)]
print(f"2. Multiplication - Python List: {time.time() - start:.5f} sec")

# NumPy
start = time.time()
result = np_a * np_b
print(f"2. Multiplication - NumPy:       {time.time() - start:.5f} sec")

2. Multiplication - Python List: 0.11159 sec
2. Multiplication - NumPy:       0.01622 sec


In [ ]:
# 3. Dot Product

# Python list
start = time.time()
dot = sum(list_a[i] * list_b[i] for i in range(SIZE))
print(f"3. Dot Product - Python List: {time.time() - start:.5f} sec")

# NumPy
start = time.time()
dot = np.dot(np_a, np_b)
print(f"3. Dot Product - NumPy:       {time.time() - start:.5f} sec")

3. Dot Product - Python List: 0.10720 sec
3. Dot Product - NumPy:       0.00190 sec


In [ ]:
# 4. Matrix Multiplication

SIZE_M = 1000

mat_a = [[1.0] * SIZE_M for _ in range(SIZE_M)]
mat_b = [[1.0] * SIZE_M for _ in range(SIZE_M)]

# Python list matrix multiply
start = time.time()
result = [[sum(mat_a[i][k] * mat_b[k][j] for k in range(SIZE_M)) for j in range(SIZE_M)] for i in range(SIZE_M)]
python_time = time.time() - start
print(f"4. Matrix Multiply - Python List: {python_time:.5f} sec")

# NumPy
np_mat_a = np.ones((1000, 1000))
np_mat_b = np.ones((1000, 1000))
start = time.time()
result = np.dot(np_mat_a, np_mat_b)
numpy_time = time.time() - start
print(f"4. Matrix Multiply - NumPy:  {numpy_time:.5f} sec")

4. Matrix Multiply - Python List: 122.00226 sec
4. Matrix Multiply - NumPy:  0.11330 sec
